<link rel="stylesheet" href="/static.css" type="text/css">

<h1 class="pgTitle">Terms of Use</h1>

<?php require_once "Sidebar.php"; ?>

<h2 class="pgTitle">1. Your Acceptance</h2> 

<p>BY USING AND/OR VISITING THIS WEBSITE (collectively, including all Content available through the EpikTube.xyz domain name, the "EpikTube Website", or "Website"), YOU SIGNIFY YOUR ASSENT TO BOTH THESE TERMS AND CONDITIONS (the "Terms of Service") AND THE TERMS AND CONDITIONS OF EPIKTUBE'S PRIVACY NOTICE, WHICH ARE PUBLISHED AT http://www.epiktube.xyz/t/privacy, AND WHICH ARE INCORPORATED HEREIN BY REFERENCE. If you do not agree to any of these terms, then please do not use the EpikTube Website. </p>

<h2 class="pgTitle">2. EpikTube Website</h2> 

<p>These Terms of Service apply to all users of the EpikTube Website, including users who are also contributors of video content, information, and other materials or services on the Website. The EpikTube Website may contain links to third party websites that are not owned or controlled by EpikTube. EpikTube has no control over, and assumes no responsibility for, the content, privacy policies, or practices of any third party websites. In addition, EpikTube will not and cannot censor or edit the content of any third-party site. By using the Website, you expressly relieve EpikTube from any and all liability arising from your use of any third-party website. Accordingly, we encourage you to be aware when you leave the EpikTube Website and to read the terms and conditions and privacy policy of each other website that you visit. </p>

<h2 class="pgTitle">3. Website Access</h2>

<p>A. EpikTube hereby grants you permission to use the Website as set forth in this Terms of Service, provided that: (i) your use of the Website as permitted is solely for your personal, noncommercial use; (ii) you will not copy or distribute any part of the Website in any medium without EpikTube's prior written authorization; (iii) you will not alter or modify any part of the Website other than as may be reasonably necessary to use the Website for its intended purpose; and (iv) you will otherwise comply with the terms and conditions of these Terms of Service.</p>

<p>B. In order to access some features of the Website, you will have to create an account. You may never use another's account without permission. When creating your account, you must provide accurate and complete information. You are solely responsible for the activity that occurs on your account, and you must keep your account password secure. You must notify EpikTube immediately of any breach of security or unauthorized use of your account. Although EpikTube will not be liable for your losses caused by any unauthorized use of your account, you may be liable for the losses of EpikTube or others due to such unauthorized use. </p>

<p>C. You agree not to use or launch any automated system, including without limitation, "robots," "spiders," "offline readers," etc., that accesses the Website in a manner that sends more request messages to the EpikTube servers in a given period of time than a human can reasonably produce in the same period by using a convention on-line web browser. Notwithstanding the foregoing, EpikTube grants the operators of public search engines permission to use spiders to copy materials from the site for the sole purpose of creating publicly available searchable indices of the materials, but not caches or archives of such materials. EpikTube reserves the right to revoke these exceptions either generally or in specific cases. You agree not to collect or harvest any personally identifiable information, including account names, from the Website, nor to use the communication systems provided by the Website for any commercial solicitation purposes. You agree not to solicit, for commercial purposes, any users of the Website with respect to their User Submissions. </p>

<h2 class="pgTitle">4. Intellectual Property Rights</h2>

<p>The content on the EpikTube Website, except all User Submissions (as defined below), including without limitation, the text, software, scripts, graphics, photos, sounds, music, videos, interactive features and the like ("Content") and the trademarks, service marks and logos contained therein ("Marks"), are owned by or licensed to EpikTube, subject to copyright and other intellectual property rights under United States and foreign laws and international conventions. Content on the Website is provided to you AS IS for your information and personal use only and may not be used, copied, reproduced, distributed, transmitted, broadcast, displayed, sold, licensed, or otherwise exploited for any other purposes whatsoever without the prior written consent of the respective owners. EpikTube reserves all rights not expressly granted in and to the Website and the Content. You agree to not engage in the use, copying, or distribution of any of the Content other than expressly permitted herein, including any use, copying, ordistribution of User Submissions of third parties obtained through the Website for any commercial purposes. If you download or print a copy of the Content for personal use, you must retain all copyright and other proprietary notices contained therein. You agree not to circumvent, disable or otherwise interfere with security related features of the EpikTube Website or features that prevent or restrict use or copying of any Content or enforce limitations on use of the EpikTube Website or the Content therein.</p>

<h2 class="pgTitle">5. User Submissions</h2>

<p>A. The EpikTube Website may now or in the future permit the submission of videos or other communications submitted by you and other users ("User Submissions") and the hosting, sharing, and/or publishing of such User Submissions. You understand that whether or not such User Submissions are published, EpikTube does not guarantee any confidentiality with respect to any submissions.</p>

<p>B. You shall be solely responsible for your own User Submissions and the consequences of posting or publishing them. In connection with User Submissions, you affirm, represent, and/or warrant that: (i) you own or have the necessary licenses, rights, consents, and permissions to use and authorize EpikTube to use all patent, trademark, trade secret, copyright or other proprietary rights in and to any and all User Submissions to enable inclusion and use of the User Submissions in the manner contemplated by the Website and these Terms of Service; and (ii) you have the written consent, release, and/or permission of each and every identifiable individual person in the User Submission to use the name or likeness of each and every such identifiable individual person to enable inclusion and use of the User Submissions in the manner contemplated by the Website and these Terms of Service. <strong>For clarity, you retain all of your ownership rights in your User Submissions</strong>. However, by submitting the User Submissions to EpikTube, you hereby grant EpikTube a worldwide, non-exclusive, royalty-free, sublicenseable and transferable license to use, reproduce, distribute, prepare derivative works of, display, and perform the User Submissions in connection with the EpikTube Website and EpikTube's (and its successor's) business, including without limitation for promoting and redistributing part or all of the EpikTube Website (and derivative works thereof) in any media formats and through any media channels. You also hereby grant each user of the EpikTube Website a non-exclusive license to access your User Submissions through the Website, and to use, reproduce, distribute, prepare derivative works of, display and perform such User Submissions as permitted through the functionality of the Website and under these Terms of Service. The foregoing license granted by you terminates once you remove or delete a User Submission from the EpikTube Website.</p>

<p>C. <strong>In connection with User Submissions, you further agree that you will not: (i) submit material that is copyrighted, protected by trade secret or otherwise subject to third party proprietary rights, including privacy and publicity rights, unless you are the owner of such rights or have permission from their rightful owner to post the material and to grant EpikTube all of the license rights granted herein; (ii) publish falsehoods or misrepresentations that could damage EpikTube or any third party; (iii) submit material that is unlawful, obscene, defamatory, libelous, threatening, pornographic, harassing, hateful, racially or ethnically offensive, or encourages conduct that would be considered a criminal offense, give rise to civil liability, violate any law, or is otherwise inappropriate; (iv) post advertisements or solicitations of business: (v) impersonate another person.</strong> EpikTube does not endorse any User Submission or any opinion, recommendation, or advice expressed therein, and EpikTube expressly disclaims any and all liability in connection with User Submissions. EpikTube does not permit copyright infringing activities and infringement of intellectual property rights on its Website, and EpikTube will remove all Content and User Submissions if properly notified that such Content or User Submission infringes on another's intellectual property rights. EpikTube reserves the right to remove Content and User Submissions without prior notice. EpikTube will also terminate a User's access to its Website, if they are determined to be a repeat infringer. A repeat infringer is a User who has been notified of infringing activity more than twice and/or has had a User Submission removed from the Website more than twice. EpikTube also reserves the right to decide whether Content or a User Submission is appropriate and complies with these Terms of Service for violations other than copyright infringement and violations of intellectual property law, such as, but not limited to, pornography, obscene or defamatory material, or excessive length. EpikTube may remove such User Submissions and/or terminate a User's access for uploading such material in violation of these Terms of Service at any time, without prior notice and at its sole discretion. </p>

<p>D. In particular, if you are a copyright owner or an agent thereof and believe that any User Submission or other content infringes upon your copyrights, you may submit a notification pursuant to the Digital Millennium Copyright Act ("DMCA") by providing our Copyright Agent with the following information in writing (see 17 U.S.C 512(c)(3) for further detail): </p>

<p>(i) A physical or electronic signature of a person authorized to act on behalf of the owner of an exclusive right that is allegedly infringed; </p>

<p>(ii) Identification of the copyrighted work claimed to have been infringed, or, if multiple copyrighted works at a single online site are covered by a single notification, a representative list of such works at that site; </p>

<p>(iii) Identification of the material that is claimed to be infringing or to be the subject of infringing activity and that is to be removed or access to which is to be disabled and information reasonably sufficient to permit the service provider to locate the material;</p>

<p>(iv) Information reasonably sufficient to permit the service provider to contact you, such as an address, telephone number, and, if available, an electronic mail; </p>

<p>(v) A statement that you have a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and </p>

<p>(vi) A statement that the information in the notification is accurate, and under penalty of perjury, that you are authorized to act on behalf of the owner of an exclusive right that is allegedly infringed. </p>

<p>EpikTube's designated Copyright Agent to receive notifications of claimed infringement is: Heather Gillette, 71 E. Third Avenue, 2nd Floor, San Mateo CA 94401, email: copyright@epiktube.xyz, telephone: 650 343-2960, fax: 650-343-2983. For clarity, only DMCA notices should go to the Copyright Agent; any other feedback, comments, requests for technical support, and other communications should be directed to EpikTube customer service through http://www.epiktube.xyz/contact.php. You acknowledge that if you fail to comply with all of the requirements of this Section 5(D), your DMCA notice may not be valid.</p>

<p>E. You understand that when using the EpikTube Website, you will be exposed to User Submissions from a variety of sources, and that EpikTube is not responsible for the accuracy, usefulness, safety, or intellectual property rights of or relating to such User Submissions. You further understand and acknowledge that you may be exposed to User Submissions that are inaccurate, offensive, indecent, or objectionable, and you agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against EpikTube with respect thereto, and agree to indemnify and hold EpikTube, its Owners/Operators, affiliates, and/or licensors, harmless to the fullest extent allowed by law regarding all matters related to your use of the site.</p>

<p>F. EpikTube permits you to link to materials on the Website for personal, non-commercial purposes only. In addition, EpikTube provides an "Embeddable Player" feature, which you may incorporate into your own personal, non-commercial websites for use in accessing the materials on the Website, provided that you include a prominent link back to the EpikTube website on the pages containing the Embeddable Player. EpikTube reserves the right to discontinue any aspect of the EpikTube Website at any time.</p>

<h2 class="pgTitle">6. Warranty Disclaimer</h2>

<p>YOU AGREE THAT YOUR USE OF THE EPIKTUBE WEBSITE SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, EPIKTUBE, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE WEBSITE AND YOUR USE THEREOF. EPIKTUBE MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THIS SITE'S CONTENT OR THE CONTENT OF ANY SITES LINKED TO THIS SITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH OUR WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONSIN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE EPIKTUBE WEBSITE. EPIKTUBE DOES NOT WARRANT, ENDORSE, GUARANTEE, OR ASSUME RESPONSIBILITY FOR ANY PRODUCT OR SERVICE ADVERTISED OR OFFERED BY A THIRD PARTY THROUGH THE EPIKTUBE WEBSITE OR ANY HYPERLINKED WEBSITE OR FEATURED IN ANY BANNER OR OTHER ADVERTISING, AND EPIKTUBE WILL NOT BE A PARTY TO OR IN ANY WAY BE RESPONSIBLE FOR MONITORING ANY TRANSACTION BETWEEN YOU AND THIRD-PARTY PROVIDERS OF PRODUCTS OR SERVICES. AS WITH THE PURCHASE OF A PRODUCT OR SERVICE THROUGH ANY MEDIUM OR IN ANY ENVIRONMENT, YOU SHOULD USE YOUR BEST JUDGMENT AND EXERCISE CAUTION WHERE APPROPRIATE.</p>

<h2 class="pgTitle">7. Limitation of Liability</h2>

<p>IN NO EVENT SHALL EPIKTUBE, ITS OFFICERS, DIRECTORS, EMPLOYEES, OR AGENTS, BE LIABLE TO YOU FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, PUNITIVE, OR CONSEQUENTIAL DAMAGES WHATSOEVER RESULTING FROM ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF OUR WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR WEBSITE, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE, WHICH MAY BE TRANSMITTED TO OR THROUGH OUR WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF YOUR USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE EPIKTUBE WEBSITE, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, AND WHETHER ORNOT THE COMPANY IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE FOREGOING LIMITATION OF LIABILITY SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW IN THE APPLICABLE JURISDICTION. </p>

<p>YOU SPECIFICALLY ACKNOWLEDGE THAT EPIKTUBE SHALL NOT BE LIABLE FOR USER SUBMISSIONS OR THE DEFAMATORY, OFFENSIVE, OR ILLEGAL CONDUCT OF ANY THIRD PARTY AND THAT THE RISK OF HARM OR DAMAGE FROM THE FOREGOING RESTS ENTIRELY WITH YOU. </p>

<p>The Website is controlled and offered by EpikTube from its facilities in the United States of America. EpikTube makes no representations that the EpikTube Website is appropriate or available for use in other locations. Those who access or use the EpikTube Website from other jurisdictions do so at their own volition and are responsible for compliance with local law. </p>

<h2 class="pgTitle">8. Indemnity</h2>

<p>You agree to defend, indemnify and hold harmless EpikTube, its parent corporation, officers, directors, employees and agents, from and against any and all claims, damages, obligations, losses, liabilities, costs or debt, and expenses (including but not limited to attorney's fees) arising from: (i) your use of and access to the EpikTube Website; (ii) your violation of any term of these Terms of Service; (iii) your violation of any third party right, including without limitation any copyright, property, or privacy right; or (iv) any claim that one of your User Submissions caused damage to a third party. This defense and indemnification obligation will survive these Terms of Service and your use of the EpikTube Website. </p>

<h2 class="pgTitle">9. Ability to Accept Terms of Service</h2>

<p>You affirm that you are either more than 18 years of age, or an emancipated minor, or possess legal parental or guardian consent, and are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide by and comply with these Terms of Service. In any case, you affirm that you are over the age of 13, as the EpikTube Website is not intended for children under 13. <strong>If you are under 13 years of age, then please do not use the EpikTube Website&#8212;there are lots of other great web sites for you. Talk to your parents about what sites are appropriate for you</strong>.</p>

<h2 class="pgTitle">10. Assignment</h2>

<p>These Terms of Service, and any rights and licenses granted hereunder, may not be transferred or assigned by you, but may be assigned by EpikTube without restriction. </p>

<h2 class="pgTitle">11. General</h2>

<p>You agree that: (i) the EpikTube Website shall be deemed solely based in Texas; and (ii) the EpikTube Website shall be deemed a passive website that does not give rise to personal jurisdiction over EpikTube, either specific or general, in jurisdictions other than Texas. These Terms of Service shall be governed by the internal substantive laws of the State of Texas, without respect to its conflict of laws principles. Any claim or dispute between you and EpikTube that arises in whole or in part from the EpikTube Website shall be decided exclusively by a court of competent jurisdiction located in Texas. These Terms of Service, together with the Privacy Notice at http://www.epiktube.xyz/t/privacy and any other legal notices published by EpikTube on the Website, shall constitute the entire agreement between you and EpikTube concerning the EpikTube Website. If any provision of these Terms of Service is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of these Terms of Service, which shall remain in full force and effect. No waiver of any term of this these Terms of Service shall be deemed a further or continuing waiver of such term or any other term, and EpikTube's failure to assert any right or provision under these Terms of Service shall not constitute a waiver of such right or provision. EpikTube reserves the right to amend these Terms of Service at any time and without notice, and it is your responsibility to review these Terms of Service for any changes. Your use of the EpikTube Website following any amendment of these Terms of Service will signify your assent to and acceptance of its revised terms. YOU AND EPIKTUBE AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE EPIKTUBE WEBSITE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</p>